import Link from 'next/link'

export default function CottageTwoPage() {
  return <main className="site-shell detail-page">
    <header className="site-header"><Link className="brand-mark" href="/"><span>KC</span><div><strong>Kenmore</strong><small>Can Be More</small></div></Link><Link className="back-link" href="/national-trust-listings">← National Trust Listings</Link></header>
    <article className="record">
      <p className="eyebrow">National Trust Register · Record 03</p>
      <h1>Cottage 2 —<br /><em>Gatekeepers Residence and Main Entrance</em></h1>
      <div className="record-meta"><span>Community Research</span><span>Last modified 21 November 2023</span></div>
      <div className="record-layout"><div className="record-main"><p className="lead">The following Description, Reason for Listing and Photo are sourced directly from the National Trust Register records, reproduced here for reference and accessibility.</p><section><h2>Description</h2><p>The small residence which forms the focus of this group was erected as part of the original suite of Kenmore buildings, 1894-95. In stylistic terms it is the building most closely resembling Richard Norman Shaw&apos;s &quot;Old English&quot; style, with a distinctive flavour of Arts and Crafts. It is located on the north side of Ross Avenue, the access road from the Main Entrance.</p><p>The house is asymmetrical in plan, double-storeyed with a roof sweeping down over the entrance porch. The roof has terracotta tiles, bracketed gables and terracotta finials. The main gable of its upper storey is jettied, bracketed and tile-hung, and has a swept skillioned window hood also supported on decorative brackets. The chimneys have pebbledash panels and terracotta pots. The porch has a semicircular arch with red brick trim and this has been filled in very sympathetically with glazed framing and a glazed door of unusual shape. Beneath the jettying of the main gable there is a faceted bay window with a frieze of pebbledash. The eaves gutters are of half-round section.</p></section><section><h2>Reason for Listing</h2><p>Part of a significant Federation period institutional complex of fine buildings and landscape. This is a handsome and unusual entrance ensemble probably designed in the office of the first Government Architect.</p></section><section><h2>Photos</h2><p>Photo record reproduced from the National Trust Register.</p></section></div><aside className="attachments"><p className="side-label">Record files</p><div className="attachment"><span className="file-icon">JPG</span><div><strong>Kenmore-Cottage2-NatTrust.jpg</strong><small>Image / reference photograph</small></div></div><div className="attachment"><span className="file-icon">PDF</span><div><strong>Kenmore Hospital 33 - cottage 2.pdf</strong><small>National Trust record</small></div></div></aside></div>
      <div className="source-note"><strong>Source</strong><span>National Trust Register — Record sighted.</span></div>
    </article><footer><span>Kenmore Can Be More</span><span>Community Research Archive · 2023</span></footer>
  </main>
}
