import Link from 'next/link'

const records: Record<string, { title: string; description: string; reason: string }> = {
  'ward-1-male-division-sick-and-infirm': { title: 'Ward 1 — Male Division — Sick and Infirm', description: 'Erected in 1894–95, this building now incorporates the Nursing Education Centre. It is two-storeyed on the access road side and single-storeyed on the airing court side. Its roofs are of slate with sheet metal trim.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-2-male-division-recent-and-acute': { title: 'Ward 2 — Male Division — Recent and Acute', description: 'Erected in 1894–95, this ward block is two storeys high on both road and court sides and has roofs of slate with sheet metal trim. A weeping willow stands in the centre of the airing court and the original pattern of curving paths survives.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-3-male-division-intermediate': { title: 'Ward 3 — Male Division — Intermediate', description: 'This ward block, finished in 1900, now has glazed terracotta tile roofs. It is two-storeyed throughout. Some of the windows are very tall, with triple casement sashes.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-4-male-division-violent-and-noisy': { title: 'Ward 4 — Male Division — Violent and Noisy', description: 'Another of the wards first occupied in 1900, this block is two-storeyed. It now houses the Resource Centre and Sewing Room. A new first-floor link connects it with the later extension to Ward 5, and some of the court verandah has been enclosed.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-5-male-division-epileptic': { title: 'Ward 5 — Male Division — Epileptic', description: 'This block, first occupied in 1900, is two-storeyed and slate-roofed. It has been extended with a two-storeyed tile-roofed block and a single-storeyed appendage. Its distinctive roof gables include a faceted timber bay and a staircase rising effectively three storeys because of the land slope.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-6-male-division-quiet-and-industrious': { title: 'Ward 6 — Male Division — Quiet and Industrious', description: 'Ward 6, erected by 1900, has been compromised by unsympathetic re-additions on the access road side and has been roofed in glazed terracotta tiling. Its airing court contains a timber-posted octagonal rotunda or gazebo with a pyramid roof and four gablets.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-8-male-convalescent-block': { title: 'Ward 8 — Male Convalescent Block', description: 'This two-storey block, probably completed by 1911, now has dark concrete tile roofing. The single-storey verandah is roofed in roll-jointed sheet metal, and the airing court area is now the hospital bowling green.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-9-male-reception-block': { title: 'Ward 9 — Male Reception Block', description: 'Wards 9, 10 and 11 were designed as a distinctive Free Style symmetrical ensemble and completed in 1911. Ward 9 is virtually symmetrical, single-storeyed, and comprises a central bay with flanking wings and an airing court on the east side. A later two-storey addition has compromised the original symmetry.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-10-sisters-quarters': { title: 'Ward 10 — Sisters Quarters', description: 'This two-storeyed block forms the centrepiece of the composition of Wards 9, 10 and 11, completed in 1911. It has moulded chimney tops, a suspended flat awning over the paired entrance doors, unusual window bays and leaded glass in Art Nouveau designs.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-11-female-reception-block': { title: 'Ward 11 — Female Reception Block', description: 'Wards 9, 10 and 11 were erected in three stages, with the first buildings dating from 1894–95 and later groups completed by 1900 and 1911. The typical ward plan included dormitories, single rooms, dining and visitor rooms, food preparation facilities, verandahs and a sunny airing court.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-12-female-convalescent-block': { title: 'Ward 12 — Female Convalescent Block', description: 'Completed, as far as known, in 1911, this building is similar in form and style to Ward 8. It has a concrete tile roof and has recently been refurbished.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-16-female-division-violent-and-noisy': { title: 'Ward 16 — Female Division — Violent and Noisy', description: 'Another ward block completed in 1900, this one matched Ward 4 in general appearance. Its main roofs are slate, while the centre bay has been reroofed in corrugated iron. An assertive first-floor link connects it to Ward 17, and the airing court verandah has been partly enclosed.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-17-female-division-intermediate': { title: 'Ward 17 — Female Division — Intermediate', description: 'This ward block was completed during the 1898–1900 building campaign. It is two-storeys high with glazed terracotta tile roofs. The airing court has no fence and includes informal tree planting.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-18-female-division-recent-and-acute': { title: 'Ward 18 — Female Division — Recent and Acute', description: 'One of the original 1894–95 wards, this block is two storeys high with slate roofs, except for the central access-road bay which has been reroofed with dark concrete tiles. The airing court contains a timber-framed, slate-roofed gazebo-rotunda.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-19-female-division-sick-and-infirm': { title: 'Ward 19 — Female Division — Sick and Infirm', description: 'One of the original 1894–95 buildings, this ward is single-storeyed on the airing side and double-storeyed on the access road side. It displays extensive refurbishment, including dark concrete tile roofing, glazed verandahs and recovered verandah roofs.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
}

export function generateStaticParams() { return Object.keys(records).map((slug) => ({ slug })) }

export default async function WardRecordPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const record = records[slug]
  if (!record) return null
  return <main className="site-shell detail-page"><header className="site-header"><Link className="brand-mark" href="/"><span>KC</span><div><strong>Kenmore</strong><small>Can Be More</small></div></Link><Link className="back-link" href="/national-trust-listings">← National Trust Listings</Link></header><article className="record"><p className="eyebrow">National Trust Register · Ward record</p><h1>{record.title}</h1><div className="record-meta"><span>Community Research</span><span>Last modified 21 November 2023</span></div><div className="record-layout"><div className="record-main"><p className="lead">The following Description, Reason for Listing and Photo are sourced directly from the National Trust Register records, reproduced here for reference and accessibility.</p><section><h2>Description</h2><p>{record.description}</p></section><section><h2>Reason for Listing</h2><p>{record.reason}</p></section><section><h2>Photos</h2><p>Photo record reproduced from the National Trust Register.</p></section></div><aside className="attachments"><p className="side-label">Record status</p><div className="attachment"><span className="file-icon">NT</span><div><strong>National Trust Register</strong><small>Record sighted · Community archive</small></div></div></aside></div><div className="source-note"><strong>Source</strong><span>National Trust Register — Record sighted.</span></div></article><footer><span>Kenmore Can Be More</span><span>Community Research Archive · 2023</span></footer></main>
}
