import Link from 'next/link'

const records: Record<string, { title: string; kind?: string; description: string | string[]; reason: string; photos?: string }> = {
  'chapel': { title: 'Chapel', kind: 'Building record', description: ['On the original drawing this is shown as though intended to be built in two stages, the first of which, the north-west half including the entrance bay, is marked as the Recreation Hall. It is assumed that this is the section completed by 1895 as part of the original suite of hospital buildings.', 'Architectural evidence indicates that the south-east part was erected either at the same time or very soon afterwards. The present building comprises a large auditorium with a chancel and vestry rooms at the north-west end and a proscenium stage at the south-east end.'], reason: 'An important social focus for the Hospital, a significant Federation period institutional complex of fine buildings and landscape. A very good example of Free Style architecture by the first Government Architect.' },
  'dental-clinic-building': { title: 'Dental Clinic Building', kind: 'Building record', description: ['Early site drawings suggest that this was originally a wing of the original Workshop complex that was burnt down, later to be replaced by the present Workshops Block. The brick wall with bullnose coping, extending northwards from the west end of the Dental Building, was evidently the wall connecting the two.', 'The building is a single-storey structure of brick, with a gabled roof of terracotta tiles. A narrow bay at the west end has a smaller gable roof surmounted by a circular metal roof vent. The most notable feature of the building is the row of wall arches formed in the north wall. They seem to have been an adaptation of earlier walling and have since been filled in with timber framed panels with windows. The triple windows in the east end appear to be original.'], reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An interesting surviving wing of an earlier building.' },
  'coorawong-house-medical-superintendent': { title: 'Coorawong House — Medical Superintendent', kind: 'Residence record', description: ['This fine building, the largest separate house at Kenmore, is believed to have been erected by 1911, for the Medical Superintendent, Dr C.A. Hogg. It is now occupied by the Department of Family and Community Services.', 'The residence is two-storeyed, with cavity walls of Goulburn face bricks laid in stretcher bond, roof forms covered in terracotta tiles and prominent, robust ribbed chimneys. There is a single-storeyed verandah with decorated square timber posts and a porch with a shingled gable. The windows have flat segmental arches of red brick and there is a band of red brickwork at the sill level of the upper windows. The double-hung windows have top sashes glazed with small panes. This assemblage of elements gives the house a distinctive Queen Anne style character.', 'The interior was inaccessible at the time of these inspections.'], reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An excellent example of Queen Anne residential architecture designed in the office of the first Government Architect.', photos: 'N/A' },
  'cottage-11-chief-attendants-residence': { title: 'Cottage 11 — Chief Attendants Residence', kind: 'Residence record', description: 'A small single-storeyed residence in the Federation Queen Anne Style, with brick walls in English bond, a terracotta tile roof of gabled hips and a parapeted and faceted bay. The chimney details match those of Cottages 1, 2 and 12. There is a verandah supported on decorated square timber posts. The windows have top sashes glazed with small panes. The house probably dates from 1911.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. A good and intact example of Queen Anne architecture probably designed in the office of the first Government Architect.' },
  'cottage-12-gardeners-residence': { title: 'Cottage 12 — Gardeners Residence', kind: 'Residence record', description: 'This small house is very similar to, but not exactly the same as, Cottage No. 11 already described. Refer to that description. The reasons for listing are the same.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. A good and intact example of Queen Anne architecture probably designed in the office of the first Government Architect.' },
  'cottage-15-carpenters-residence': { title: 'Cottage 15 — Carpenters Residence', kind: 'Residence record', description: 'This residence, now the venue for the Social Welfare Department of the Hospital, is a small single-storeyed T-shaped brick building, to which timber additions have been made. Around three sides of the room which projects to the west there is a verandah on timber posts. The roof is of terracotta tiles, the brickwork is laid in English bond and there is a polygonal bay with faceted roof.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. A good intact example of a small residence designed in the office of the first Government Architect.' },
  'ward-1-male-division-sick-and-infirm': { title: 'Ward 1 — Male Division — Sick and Infirm', description: 'Erected in 1894–95, this building now incorporates the Nursing Education Centre. It is two-storeyed on the access road side and single-storeyed on the airing court side. Its roofs are of slate with sheet metal trim.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-2-male-division-recent-and-acute': { title: 'Ward 2 — Male Division — Recent and Acute', description: 'Erected in 1894–95, this ward block is two storeys high on both road and court sides and has roofs of slate with sheet metal trim. A weeping willow stands in the centre of the airing court and the original pattern of curving paths survives.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-3-male-division-intermediate': { title: 'Ward 3 — Male Division — Intermediate', description: 'This ward block, finished in 1900, now has glazed terracotta tile roofs. It is two-storeyed throughout. Some of the windows are very tall, with triple casement sashes.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-4-male-division-violent-and-noisy': { title: 'Ward 4 — Male Division — Violent and Noisy', description: 'Another of the wards first occupied in 1900, this block is two-storeyed. It now houses the Resource Centre and Sewing Room. A new first-floor link connects it with the later extension to Ward 5, and some of the court verandah has been enclosed.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-5-male-division-epileptic': { title: 'Ward 5 — Male Division — Epileptic', description: 'This block, first occupied in 1900, is two-storeyed and slate-roofed. It has been extended with a two-storeyed tile-roofed block and a single-storeyed appendage. Its distinctive roof gables include a faceted timber bay and a staircase rising effectively three storeys because of the land slope.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-6-male-division-quiet-and-industrious': { title: 'Ward 6 — Male Division — Quiet and Industrious', description: 'Ward 6, erected by 1900, has been compromised by unsympathetic re-additions on the access road side and has been roofed in glazed terracotta tiling. Its airing court contains a timber-posted octagonal rotunda or gazebo with a pyramid roof and four gablets.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-8-male-convalescent-block': { title: 'Ward 8 — Male Convalescent Block', description: 'This two-storey block, probably completed by 1911, now has dark concrete tile roofing. The single-storey verandah is roofed in roll-jointed sheet metal, and the airing court area is now the hospital bowling green.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-9-male-reception-block': { title: 'Ward 9 — Male Reception Block', description: 'Wards 9, 10 and 11 were designed as a distinctive Free Style symmetrical ensemble and completed in 1911. Ward 9 is virtually symmetrical, single-storeyed, and comprises a central bay with flanking wings and an airing court on the east side. A later two-storey addition has compromised the original symmetry.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-10-sisters-quarters': { title: 'Ward 10 — Sisters Quarters', description: 'This two-storeyed block forms the centrepiece of the composition of Wards 9, 10 and 11, completed in 1911. It has moulded chimney tops, a suspended flat awning over the paired entrance doors, unusual window bays and leaded glass in Art Nouveau designs.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-11-female-reception-block': { title: 'Ward 11 — Female Reception Block', description: 'Wards 9, 10 and 11 were erected in three stages, with the first buildings dating from 1894–95 and later groups completed by 1900 and 1911. The typical ward plan included dormitories, single rooms, dining and visitor rooms, food preparation facilities, verandahs and a sunny airing court.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-12-female-convalescent-block': { title: 'Ward 12 — Female Convalescent Block', description: 'Completed, as far as known, in 1911, this building is similar in form and style to Ward 8. It has a concrete tile roof and has recently been refurbished.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-16-female-division-violent-and-noisy': { title: 'Ward 16 — Female Division — Violent and Noisy', description: 'Another ward block completed in 1900, this one matched Ward 4 in general appearance. Its main roofs are slate, while the centre bay has been reroofed in corrugated iron. An assertive first-floor link connects it to Ward 17, and the airing court verandah has been partly enclosed.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-17-female-division-intermediate': { title: 'Ward 17 — Female Division — Intermediate', description: 'This ward block was completed during the 1898–1900 building campaign. It is two-storeys high with glazed terracotta tile roofs. The airing court has no fence and includes informal tree planting.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-18-female-division-recent-and-acute': { title: 'Ward 18 — Female Division — Recent and Acute', description: 'One of the original 1894–95 wards, this block is two storeys high with slate roofs, except for the central access-road bay which has been reroofed with dark concrete tiles. The airing court contains a timber-framed, slate-roofed gazebo-rotunda.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
  'ward-19-female-division-sick-and-infirm': { title: 'Ward 19 — Female Division — Sick and Infirm', description: 'One of the original 1894–95 buildings, this ward is single-storeyed on the airing side and double-storeyed on the access road side. It displays extensive refurbishment, including dark concrete tile roofing, glazed verandahs and recovered verandah roofs.', reason: 'Part of a significant Federation period institutional complex of fine buildings and landscape. An outstanding example of Free Style architecture by the first Government Architect.' },
}

export function generateStaticParams() { return Object.keys(records).map((slug) => ({ slug })) }

export default async function WardRecordPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const record = records[slug]
  if (!record) return null
  return <main className="site-shell detail-page"><header className="site-header"><Link className="brand-mark" href="/"><span>KC</span><div><strong>Kenmore</strong><small>Can Be More</small></div></Link><Link className="back-link" href="/national-trust-listings">← National Trust Listings</Link></header><article className="record"><p className="eyebrow">National Trust Register · {record.kind ?? 'Ward record'}</p><h1>{record.title}</h1><div className="record-meta"><span>Community Research</span><span>Last modified 21 November 2023</span></div><div className="record-layout"><div className="record-main"><p className="lead">The following Description, Reason for Listing and Photo are sourced directly from the National Trust Register records, reproduced here for reference and accessibility.</p><section><h2>Description</h2>{(Array.isArray(record.description) ? record.description : [record.description]).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section><section><h2>Reason for Listing</h2><p>{record.reason}</p></section><section><h2>Photos</h2><p>{record.photos ?? 'Photo record reproduced from the National Trust Register.'}</p></section></div><aside className="attachments"><p className="side-label">Record status</p><div className="attachment"><span className="file-icon">NT</span><div><strong>National Trust Register</strong><small>Record sighted · Community archive</small></div></div></aside></div><div className="source-note"><strong>Source</strong><span>National Trust Register — Record sighted.</span></div></article><footer><span>Kenmore Can Be More</span><span>Community Research Archive · 2023</span></footer></main>
}
